name: Docker (dev)

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.11.1
      - uses: docker/metadata-action@v5.8.0
        id: meta
        with:
          images: ghcr.io/dusk-labs/dim
      - uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          platforms: linux/amd64
          tags: ghcr.io/dusk-labs/dim:dev
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
