name: Docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "sqlite://./dim_dev.db"

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libva-dev libva-drm2 libva2 sqlite3
      - uses: actions/checkout@v5.0.0

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable

      - name: Build Docs
        run: cargo doc --verbose --workspace --release --no-deps

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: docs
          folder: target/doc
          target-folder: ${{ github.ref_name }}
