name: Rust

on: [pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "sqlite://./dim_dev.db"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libva-dev libva-drm2 libva2 sqlite3 ffmpeg
      - uses: actions/checkout@v5.0.0

      # - name: Download UI artifacts
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     workflow: react.yml
      #     workflow_conclusion: success
      #     branch: master
      #     name: webui
      #     path: ui/build
      #     repo: ${{github.repository}}

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable

      - name: Download ffmpeg + ffprobe
        run: |
          set -euxo pipefail
          version="ffmpeg-all-0.0.1"
          base="https://github.com/Dusk-Labs/ffmpeg-static/releases/download/${version}"
          curl -fL "${base}/ffmpeg"  -o ffmpeg
          curl -fL "${base}/ffprobe" -o ffprobe

      - name: Create release dir
        run: |
          mkdir -p release/utils
          cp ffmpeg release/utils/ffmpeg
          cp ffprobe release/utils/ffprobe
          chmod +x release/utils/ffmpeg
          chmod +x release/utils/ffprobe

      - name: Test Dim
        run: cargo test --tests

      - name: Build Dim
        run: cargo build --verbose --release

      - name: Copy dim binaries
        run: |
          cp target/release/dim release/dim
          chmod +x release/dim

      - name: Compress release dir
        run: tar -zcvf release.tar.gz release

      - name: Save artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: release
          path: release.tar.gz
